/**
 ******************************************************************************
 * @file      startup_stm32mp157cacx.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32MP157CACx device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m4
.fpu softvfp
.thumb

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

.equ  BootRAM,        0xF1E0F85F
/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */
/* Call the clock system intitialization function.*/
  bl  SystemInit

/* Copy the data segment initializers from flash to SRAM */
  movs	r1, #0
  b	LoopCopyDataInit

CopyDataInit:
	ldr	r3, =_sidata
	ldr	r3, [r3, r1]
	str	r3, [r0, r1]
	adds	r1, r1, #4

LoopCopyDataInit:
	ldr	r0, =_sdata
	ldr	r3, =_edata
	adds	r2, r0, r1
	cmp	r2, r3
	bcc	CopyDataInit
	ldr	r2, =_sbss
	b	LoopFillZerobss
/* Zero fill the bss segment. */
FillZerobss:
	movs r3, #0
 	str  r3, [r2]
	adds r2, r2, #4

LoopFillZerobss:
	ldr	r3, = _ebss
	cmp	r2, r3
	bcc	FillZerobss

/* Call static constructors */
    bl __libc_init_array
/* Call the application's entry point.*/
	bl	main

LoopForever:
    b LoopForever

.size	Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
    .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler
/******************************************************************************
*
* The STM32MP157CACx vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/
   .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors


g_pfnVectors:
  .word  _estack
  .word  Reset_Handler
  .word  NMI_Handler
  .word  HardFault_Handler
  .word	MemManage_Handler
  .word	BusFault_Handler
  .word	UsageFault_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	DebugMon_Handler
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	WWDG1_IT_IRQHandler        			/* Window Watchdog interrupt                              */
  .word	PVD_AVD_IRQHandler         			/* PVD AND AVD detector through EXTI                      */
  .word	TAMP_IRQHandler            			/* Tamper interrupt (include LSECSS interrupts)           */
  .word	RTC_WKUP_ALARM_IRQHandler  			/* RTC Tamper or TimeStamp                                */
  .word	TZC_IT_IRQHandler          			/* TrustZone DDR address space controller                 */
  .word	RCC_IRQHandler             			/* RCC global interrupt                                   */
  .word	EXTI0_IRQHandler           			/* EXTI Line 0 interrupt                                  */
  .word	EXTI1_IRQHandler           			/* EXTI Line 1 interrupt                                  */
  .word	EXTI2_IRQHandler           			/* EXTI Line 2 interrupt                                  */
  .word	EXTI3_IRQHandler           			/* EXTI Line 3 interrupt                                  */
  .word	EXTI4_IRQHandler           			/* EXTI Line 4 interrupt                                  */
  .word	DMA1_STR0_IRQHandler       			/* DMA1 stream0 global interrupt                          */
  .word	DMA1_STR1_IRQHandler       			/* DMA1 stream1 global interrupt                          */
  .word	DMA1_STR2_IRQHandler       			/* DMA1 stream2 global interrupt                          */
  .word	DMA1_STR3_IRQHandler       			/* DMA1 stream3 global interrupt                          */
  .word	DMA1_STR4_IRQHandler       			/* DMA1 stream4 global interrupt                          */
  .word	DMA1_STR5_IRQHandler       			/* DMA1 stream5 global interrupt                          */
  .word	DMA1_STR6_IRQHandler       			/* DMA1 stream6 global interrupt                          */
  .word	ADC1_IRQHandler            			/* ADC1 global interrupt                                  */
  .word	FDCAN1_IT0_IRQHandler      			/* FDCAN1 interrupt 0                                     */
  .word	FDCAN2_IT0_IRQHandler      			/* FDCAN2 interrupt 0                                     */
  .word	FDCAN1_IT1_IRQHandler      			/* FDCAN1 interrupt 1                                     */
  .word	FDCAN2_IT1_IRQHandler      			/* FDCAN2 interrupt 1                                     */
  .word	EXTI5_IRQHandler           			/* EXTI line 5 interrupt                                  */
  .word	TIM1_BRK_IRQHandler        			/* TIM1 break interrupt                                   */
  .word	TIM1_UP_IRQHandler         			/* TIM1 update interrupt                                  */
  .word	TIM1_TRG_COM_IRQHandler    			/* TIM1 trigger and commutation interrupt                 */
  .word	TIM1_CC_IRQHandler         			/* TIM1 capture compare interrupt                         */
  .word	TIM2_IRQHandler            			/* TIM2 global interrupt                                  */
  .word	TIM3_IRQHandler            			/* TIM3 global interrupt                                  */
  .word	TIM4_IRQHandler            			/* TIM4 global interrupt                                  */
  .word	I2C1_EVT_IRQHandler        			/* I2C1 event interrupt                                   */
  .word	I2C1_ERR_IRQHandler        			/* I2C1 global error interrupt                            */
  .word	I2C2_EVT_IRQHandler        			/* I2C2 event interrupt                                   */
  .word	I2C2_ERR_IRQHandler        			/* I2C2 global error interrupt                            */
  .word	SPI1_IRQHandler            			/* SPI1 global interrupt                                  */
  .word	SPI2_IRQHandler            			/* SPI2 global interrupt                                  */
  .word	USART1_IRQHandler          			/* USART1 global interrupt                                */
  .word	USART2_IRQHandler          			/* USART2 global interrupt                                */
  .word	USART3_IRQHandler          			/* USART3 global interrupt                                */
  .word	EXTI10_IRQHandler          			/* EXTI line 10 interrupt                                 */
  .word	RTC_TS_IRQHandler          			/* RTC timestamp interrupt                                */
  .word	EXTI11_IRQHandler          			/* EXTI line 11 interrupt                                 */
  .word	TIM8_BRK_IRQHandler        			/* TIM8 break interrupt                                   */
  .word	TIM8_UP_IRQHandler         			/* TIM8 update interrupt                                  */
  .word	TIM8_TRG_COM_IRQHandler    			/* TIM8 trigger and commutation interrupt                 */
  .word	TIM8_CC_IRQHandler         			/* TIM8 capture compare interrupt                         */
  .word	DMA1_STR7_IRQHandler       			/* DMA1 stream7 global interrupt                          */
  .word	FMC_IRQHandler             			/* FMC global interrupt                                   */
  .word	SDMMC1_IRQHandler          			/* SDMMC1 global interrupt                                */
  .word	TIM5_IRQHandler            			/* TIM5 global interrupt                                  */
  .word	SPI3_IRQHandler            			/* SPI3 global interrupt                                  */
  .word	USART4_IRQHandler          			/* USART4 global interrupt                                */
  .word	USART5_IRQHandler          			/* USART5 global interrupt                                */
  .word	TIM6_IRQHandler            			/* TIM6 global interrupt                                  */
  .word	TIM7_IRQHandler            			/* TIM7 global interrupt                                  */
  .word	DMA2_STR0_IRQHandler       			/* DMA2 stream0 global interrupt                          */
  .word	DMA2_STR1_IRQHandler       			/* DMA2 stream1 global interrupt                          */
  .word	DMA2_STR2_IRQHandler       			/* DMA2 stream2 global interrupt                          */
  .word	DMA2_STR3_IRQHandler       			/* DMA2 stream3 global interrupt                          */
  .word	DMA2_STR4_IRQHandler       			/* DMA2 stream4 global interrupt                          */
  .word	ETH1_IRQHandler            			/* ETH1 global interrupt                                  */
  .word	ETH1_WKUP_IRQHandler       			/* ETH1 wakeup interrupt                                  */
  .word	0                          			/* Reserved                                               */
  .word	EXTI6_IRQHandler           			/* EXTI line 6 interrupt                                  */
  .word	EXTI7_IRQHandler           			/* EXTI line 7 interrupt                                  */
  .word	EXTI8_IRQHandler           			/* EXTI line 8 interrupt                                  */
  .word	EXTI9_IRQHandler           			/* EXTI line 9 interrupt                                  */
  .word	DMA2_STR5_IRQHandler       			/* DMA2 stream5 global interrupt                          */
  .word	DMA2_STR6_IRQHandler       			/* DMA2 stream6 global interrupt                          */
  .word	DMA2_STR7_IRQHandler       			/* DMA2 stream7 global interrupt                          */
  .word	USART6_IRQHandler          			/* USART6 global interrupt                                */
  .word	I2C3_EVT_IRQHandler        			/* I2C3 event interrupt                                   */
  .word	I2C3_ERR_IRQHandler        			/* I2C3 global error interrupt                            */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	EXTI12_IRQHandler          			/* EXTI line 12 interrupt                                 */
  .word	EXTI13_IRQHandler          			/* EXTI line 13 interrupt                                 */
  .word	DCMI_IRQHandler            			/* DCMI global interrupt                                  */
  .word	CRYP1_IRQHandler           			/* CRYP1 global interrupt                                 */
  .word	HASH1_IRQHandler           			/* HASH1 interrupt                                        */
  .word	0                          			/* Reserved                                               */
  .word	USART7_IRQHandler          			/* USART7 global interrupt                                */
  .word	USART8_IRQHandler          			/* USART8 global interrupt                                */
  .word	SPI4_IRQHandler            			/* SPI4 global interrupt                                  */
  .word	SPI5_IRQHandler            			/* SPI5 global interrupt                                  */
  .word	SPI6_IRQHandler            			/* SPI6 global interrupt                                  */
  .word	SAI1_IRQHandler            			/* SAI1 global interrupt                                  */
  .word	LTDC_IRQHandler            			/* LTCD global interrupt                                  */
  .word	LTDC_ER_IRQHandler         			/* LTCD global error interrupt                            */
  .word	ADC2_IRQHandler            			/* ADC2 global interrupt                                  */
  .word	SAI2_IRQHandler            			/* SAI2 global interrupt                                  */
  .word	QUADSPI_IRQHandler         			/* QUADSPI global interrupt                               */
  .word	LPTIM1_IRQHandler          			/* LPTIMER1 global interrupt                              */
  .word	CEC_IRQHandler             			/* HDMI-CEC global interrupt                              */
  .word	I2C4_EVT_IRQHandler        			/* I2C4 event interrupt                                   */
  .word	I2C4_ERR_IRQHandler        			/* I2C4 global error interrupt                            */
  .word	SPDIFRX_IRQHandler         			/* SPDIFRX global interrupt                               */
  .word	OTG_IRQHandler             			/* USB On-The-Go global interrupt                         */
  .word	0                          			/* Reserved                                               */
  .word	IPCC_RX0_IRQHandler        			/* IPCC RX0 occupied interrupt                            */
  .word	IPCC_TX0_IRQHandler        			/* IPCC TX0 free interrupt                                */
  .word	DMAMUX1_OVR_REQ_IRQHandler 			/* DMAMUX1 overrun interrupt                              */
  .word	IPCC_RX1_IRQHandler        			/* IPCC RX1 occupied interrupt                            */
  .word	IPCC_TX1_IRQHandler        			/* IPCC TX1 free interrupt                                */
  .word	CRYP2_IRQHandler           			/* CRYP2 global interrupt                                 */
  .word	HASH2_IRQHandler           			/* HASH2 interrupt                                        */
  .word	I2C5_EVT_IRQHandler        			/* I2C5 event interrupt                                   */
  .word	I2C5_ERR_IRQHandler        			/* I2C5 global error interrupt                            */
  .word	0                          			/* Reserved                                               */
  .word	DFSDM1_FLT0_IRQHandler     			/* DFSDM1 filter0 Interrupt                               */
  .word	DFSDM1_FLT1_IRQHandler     			/* DFSDM1 filter1 Interrupt                               */
  .word	DFSDM1_FLT2_IRQHandler     			/* DFSDM1 filter2 Interrupt                               */
  .word	DFSDM1_FLT3_IRQHandler     			/* DFSDM1 filter3 Interrupt                               */
  .word	SAI3_IRQHandler            			/* SAI3 global interrupt                                  */
  .word	DFSDM1_FLT4_IRQHandler     			/* DFSDM1 filter4 Interrupt                               */
  .word	TIM15_IRQHandler           			/* TIM15 global interrupt                                 */
  .word	TIM16_IRQHandler           			/* TIM16 global interrupt                                 */
  .word	TIM17_IRQHandler           			/* TIM17 global interrupt                                 */
  .word	TIM12_IRQHandler           			/* TIM12 gloabl interrupt                                 */
  .word	MDIOS_IRQHandler           			/* MDIOS global interrupt                                 */
  .word	EXTI14_IRQHandler          			/* EXTI line 14 interrupt                                 */
  .word	MDMA_IRQHandler            			/* MDMA global interrupt                                  */
  .word	DSI_IRQHandler             			/* DSI Host controller global interrupt                   */
  .word	SDMMC2_IRQHandler          			/* SDMMC2 global interrupt                                */
  .word	HSEM_IT2_IRQHandler        			/* HSEM semaphore interrupt 2                             */
  .word	DFSDM1_FLT5_IRQHandler     			/* DFSDM1 filter5 Interrupt                               */
  .word	EXTI15_IRQHandler          			/* EXTI line 15 interrupt                                 */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	TIM13_IRQHandler           			/* TIM13 global interrupt                                 */
  .word	TIM14_IRQHandler           			/* TIM14 global interrupt                                 */
  .word	DAC_IRQHandler             			/* DAC1 and DAC2 underrun error interrupts                */
  .word	RNG1_IRQHandler            			/* RNG1 interrupt                                         */
  .word	RNG2_IRQHandler            			/* RNG2 interrupt                                         */
  .word	I2C6_EVT_IRQHandler        			/* I2C6 event interrupt                                   */
  .word	I2C6_ERR_IRQHandler        			/* I2C6 global error interrupt                            */
  .word	SDMMC3_IRQHandler          			/* SDMMC3 global interrupt                                */
  .word	LPTIM2_IRQHandler          			/* LPTIMER2 global interrupt                              */
  .word	LPTIM3_IRQHandler          			/* LPTIMER3 global interrupt                              */
  .word	LPTIM4_IRQHandler          			/* LPTIMER4 global interrupt                              */
  .word	LPTIM5_IRQHandler          			/* LPTIMER5 global interrupt                              */
  .word	ETH1_LPI_IRQHandler        			/* ETH1 LPI interrupt                                     */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	RCC_WAKEUP_IRQHandler      			/* RCC MPU wakeup interrupt                               */
  .word	SAI4_IRQHandler            			/* SAI4 global interrupt                                  */
  .word	DTS_IRQHandler             			/* Digital temperature sensor interrupt                   */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	IWDG1_IT_IRQHandler        			/* IWDG1 early wake                                       */
  .word	IWDG2_IT_IRQHandler        			/* IWDG2 early wake                                       */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	TAMP_S_IRQHandler          			/* TAMP tamper secure interrupt                           */
  .word	RTC_WKUP_ALARM_S_IRQHandler			/* RTC wakeup timer and alarms (A and B) secure interrupt */
  .word	RTC_TS_S_IRQHandler        			/* RTC timestamp secure interrupt                         */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	0                          			/* Reserved                                               */
  .word	DDRPERFM_IRQHandler        			/* DDR performance monitor interrupt                      */

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

  	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

  	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

  	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

  	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	WWDG1_IT_IRQHandler
	.thumb_set WWDG1_IT_IRQHandler,Default_Handler

	.weak	PVD_AVD_IRQHandler
	.thumb_set PVD_AVD_IRQHandler,Default_Handler

	.weak	TAMP_IRQHandler
	.thumb_set TAMP_IRQHandler,Default_Handler

	.weak	RTC_WKUP_ALARM_IRQHandler
	.thumb_set RTC_WKUP_ALARM_IRQHandler,Default_Handler

	.weak	TZC_IT_IRQHandler
	.thumb_set TZC_IT_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	DMA1_STR0_IRQHandler
	.thumb_set DMA1_STR0_IRQHandler,Default_Handler

	.weak	DMA1_STR1_IRQHandler
	.thumb_set DMA1_STR1_IRQHandler,Default_Handler

	.weak	DMA1_STR2_IRQHandler
	.thumb_set DMA1_STR2_IRQHandler,Default_Handler

	.weak	DMA1_STR3_IRQHandler
	.thumb_set DMA1_STR3_IRQHandler,Default_Handler

	.weak	DMA1_STR4_IRQHandler
	.thumb_set DMA1_STR4_IRQHandler,Default_Handler

	.weak	DMA1_STR5_IRQHandler
	.thumb_set DMA1_STR5_IRQHandler,Default_Handler

	.weak	DMA1_STR6_IRQHandler
	.thumb_set DMA1_STR6_IRQHandler,Default_Handler

	.weak	ADC1_IRQHandler
	.thumb_set ADC1_IRQHandler,Default_Handler

	.weak	FDCAN1_IT0_IRQHandler
	.thumb_set FDCAN1_IT0_IRQHandler,Default_Handler

	.weak	FDCAN2_IT0_IRQHandler
	.thumb_set FDCAN2_IT0_IRQHandler,Default_Handler

	.weak	FDCAN1_IT1_IRQHandler
	.thumb_set FDCAN1_IT1_IRQHandler,Default_Handler

	.weak	FDCAN2_IT1_IRQHandler
	.thumb_set FDCAN2_IT1_IRQHandler,Default_Handler

	.weak	EXTI5_IRQHandler
	.thumb_set EXTI5_IRQHandler,Default_Handler

	.weak	TIM1_BRK_IRQHandler
	.thumb_set TIM1_BRK_IRQHandler,Default_Handler

	.weak	TIM1_UP_IRQHandler
	.thumb_set TIM1_UP_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_IRQHandler
	.thumb_set TIM1_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	I2C1_EVT_IRQHandler
	.thumb_set I2C1_EVT_IRQHandler,Default_Handler

	.weak	I2C1_ERR_IRQHandler
	.thumb_set I2C1_ERR_IRQHandler,Default_Handler

	.weak	I2C2_EVT_IRQHandler
	.thumb_set I2C2_EVT_IRQHandler,Default_Handler

	.weak	I2C2_ERR_IRQHandler
	.thumb_set I2C2_ERR_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	EXTI10_IRQHandler
	.thumb_set EXTI10_IRQHandler,Default_Handler

	.weak	RTC_TS_IRQHandler
	.thumb_set RTC_TS_IRQHandler,Default_Handler

	.weak	EXTI11_IRQHandler
	.thumb_set EXTI11_IRQHandler,Default_Handler

	.weak	TIM8_BRK_IRQHandler
	.thumb_set TIM8_BRK_IRQHandler,Default_Handler

	.weak	TIM8_UP_IRQHandler
	.thumb_set TIM8_UP_IRQHandler,Default_Handler

	.weak	TIM8_TRG_COM_IRQHandler
	.thumb_set TIM8_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM8_CC_IRQHandler
	.thumb_set TIM8_CC_IRQHandler,Default_Handler

	.weak	DMA1_STR7_IRQHandler
	.thumb_set DMA1_STR7_IRQHandler,Default_Handler

	.weak	FMC_IRQHandler
	.thumb_set FMC_IRQHandler,Default_Handler

	.weak	SDMMC1_IRQHandler
	.thumb_set SDMMC1_IRQHandler,Default_Handler

	.weak	TIM5_IRQHandler
	.thumb_set TIM5_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	USART4_IRQHandler
	.thumb_set USART4_IRQHandler,Default_Handler

	.weak	USART5_IRQHandler
	.thumb_set USART5_IRQHandler,Default_Handler

	.weak	TIM6_IRQHandler
	.thumb_set TIM6_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	DMA2_STR0_IRQHandler
	.thumb_set DMA2_STR0_IRQHandler,Default_Handler

	.weak	DMA2_STR1_IRQHandler
	.thumb_set DMA2_STR1_IRQHandler,Default_Handler

	.weak	DMA2_STR2_IRQHandler
	.thumb_set DMA2_STR2_IRQHandler,Default_Handler

	.weak	DMA2_STR3_IRQHandler
	.thumb_set DMA2_STR3_IRQHandler,Default_Handler

	.weak	DMA2_STR4_IRQHandler
	.thumb_set DMA2_STR4_IRQHandler,Default_Handler

	.weak	ETH1_IRQHandler
	.thumb_set ETH1_IRQHandler,Default_Handler

	.weak	ETH1_WKUP_IRQHandler
	.thumb_set ETH1_WKUP_IRQHandler,Default_Handler

	.weak	EXTI6_IRQHandler
	.thumb_set EXTI6_IRQHandler,Default_Handler

	.weak	EXTI7_IRQHandler
	.thumb_set EXTI7_IRQHandler,Default_Handler

	.weak	EXTI8_IRQHandler
	.thumb_set EXTI8_IRQHandler,Default_Handler

	.weak	EXTI9_IRQHandler
	.thumb_set EXTI9_IRQHandler,Default_Handler

	.weak	DMA2_STR5_IRQHandler
	.thumb_set DMA2_STR5_IRQHandler,Default_Handler

	.weak	DMA2_STR6_IRQHandler
	.thumb_set DMA2_STR6_IRQHandler,Default_Handler

	.weak	DMA2_STR7_IRQHandler
	.thumb_set DMA2_STR7_IRQHandler,Default_Handler

	.weak	USART6_IRQHandler
	.thumb_set USART6_IRQHandler,Default_Handler

	.weak	I2C3_EVT_IRQHandler
	.thumb_set I2C3_EVT_IRQHandler,Default_Handler

	.weak	I2C3_ERR_IRQHandler
	.thumb_set I2C3_ERR_IRQHandler,Default_Handler

	.weak	EXTI12_IRQHandler
	.thumb_set EXTI12_IRQHandler,Default_Handler

	.weak	EXTI13_IRQHandler
	.thumb_set EXTI13_IRQHandler,Default_Handler

	.weak	DCMI_IRQHandler
	.thumb_set DCMI_IRQHandler,Default_Handler

	.weak	CRYP1_IRQHandler
	.thumb_set CRYP1_IRQHandler,Default_Handler

	.weak	HASH1_IRQHandler
	.thumb_set HASH1_IRQHandler,Default_Handler

	.weak	USART7_IRQHandler
	.thumb_set USART7_IRQHandler,Default_Handler

	.weak	USART8_IRQHandler
	.thumb_set USART8_IRQHandler,Default_Handler

	.weak	SPI4_IRQHandler
	.thumb_set SPI4_IRQHandler,Default_Handler

	.weak	SPI5_IRQHandler
	.thumb_set SPI5_IRQHandler,Default_Handler

	.weak	SPI6_IRQHandler
	.thumb_set SPI6_IRQHandler,Default_Handler

	.weak	SAI1_IRQHandler
	.thumb_set SAI1_IRQHandler,Default_Handler

	.weak	LTDC_IRQHandler
	.thumb_set LTDC_IRQHandler,Default_Handler

	.weak	LTDC_ER_IRQHandler
	.thumb_set LTDC_ER_IRQHandler,Default_Handler

	.weak	ADC2_IRQHandler
	.thumb_set ADC2_IRQHandler,Default_Handler

	.weak	SAI2_IRQHandler
	.thumb_set SAI2_IRQHandler,Default_Handler

	.weak	QUADSPI_IRQHandler
	.thumb_set QUADSPI_IRQHandler,Default_Handler

	.weak	LPTIM1_IRQHandler
	.thumb_set LPTIM1_IRQHandler,Default_Handler

	.weak	CEC_IRQHandler
	.thumb_set CEC_IRQHandler,Default_Handler

	.weak	I2C4_EVT_IRQHandler
	.thumb_set I2C4_EVT_IRQHandler,Default_Handler

	.weak	I2C4_ERR_IRQHandler
	.thumb_set I2C4_ERR_IRQHandler,Default_Handler

	.weak	SPDIFRX_IRQHandler
	.thumb_set SPDIFRX_IRQHandler,Default_Handler

	.weak	OTG_IRQHandler
	.thumb_set OTG_IRQHandler,Default_Handler

	.weak	IPCC_RX0_IRQHandler
	.thumb_set IPCC_RX0_IRQHandler,Default_Handler

	.weak	IPCC_TX0_IRQHandler
	.thumb_set IPCC_TX0_IRQHandler,Default_Handler

	.weak	DMAMUX1_OVR_REQ_IRQHandler
	.thumb_set DMAMUX1_OVR_REQ_IRQHandler,Default_Handler

	.weak	IPCC_RX1_IRQHandler
	.thumb_set IPCC_RX1_IRQHandler,Default_Handler

	.weak	IPCC_TX1_IRQHandler
	.thumb_set IPCC_TX1_IRQHandler,Default_Handler

	.weak	CRYP2_IRQHandler
	.thumb_set CRYP2_IRQHandler,Default_Handler

	.weak	HASH2_IRQHandler
	.thumb_set HASH2_IRQHandler,Default_Handler

	.weak	I2C5_EVT_IRQHandler
	.thumb_set I2C5_EVT_IRQHandler,Default_Handler

	.weak	I2C5_ERR_IRQHandler
	.thumb_set I2C5_ERR_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT0_IRQHandler
	.thumb_set DFSDM1_FLT0_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT1_IRQHandler
	.thumb_set DFSDM1_FLT1_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT2_IRQHandler
	.thumb_set DFSDM1_FLT2_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT3_IRQHandler
	.thumb_set DFSDM1_FLT3_IRQHandler,Default_Handler

	.weak	SAI3_IRQHandler
	.thumb_set SAI3_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT4_IRQHandler
	.thumb_set DFSDM1_FLT4_IRQHandler,Default_Handler

	.weak	TIM15_IRQHandler
	.thumb_set TIM15_IRQHandler,Default_Handler

	.weak	TIM16_IRQHandler
	.thumb_set TIM16_IRQHandler,Default_Handler

	.weak	TIM17_IRQHandler
	.thumb_set TIM17_IRQHandler,Default_Handler

	.weak	TIM12_IRQHandler
	.thumb_set TIM12_IRQHandler,Default_Handler

	.weak	MDIOS_IRQHandler
	.thumb_set MDIOS_IRQHandler,Default_Handler

	.weak	EXTI14_IRQHandler
	.thumb_set EXTI14_IRQHandler,Default_Handler

	.weak	MDMA_IRQHandler
	.thumb_set MDMA_IRQHandler,Default_Handler

	.weak	DSI_IRQHandler
	.thumb_set DSI_IRQHandler,Default_Handler

	.weak	SDMMC2_IRQHandler
	.thumb_set SDMMC2_IRQHandler,Default_Handler

	.weak	HSEM_IT2_IRQHandler
	.thumb_set HSEM_IT2_IRQHandler,Default_Handler

	.weak	DFSDM1_FLT5_IRQHandler
	.thumb_set DFSDM1_FLT5_IRQHandler,Default_Handler

	.weak	EXTI15_IRQHandler
	.thumb_set EXTI15_IRQHandler,Default_Handler

	.weak	TIM13_IRQHandler
	.thumb_set TIM13_IRQHandler,Default_Handler

	.weak	TIM14_IRQHandler
	.thumb_set TIM14_IRQHandler,Default_Handler

	.weak	DAC_IRQHandler
	.thumb_set DAC_IRQHandler,Default_Handler

	.weak	RNG1_IRQHandler
	.thumb_set RNG1_IRQHandler,Default_Handler

	.weak	RNG2_IRQHandler
	.thumb_set RNG2_IRQHandler,Default_Handler

	.weak	I2C6_EVT_IRQHandler
	.thumb_set I2C6_EVT_IRQHandler,Default_Handler

	.weak	I2C6_ERR_IRQHandler
	.thumb_set I2C6_ERR_IRQHandler,Default_Handler

	.weak	SDMMC3_IRQHandler
	.thumb_set SDMMC3_IRQHandler,Default_Handler

	.weak	LPTIM2_IRQHandler
	.thumb_set LPTIM2_IRQHandler,Default_Handler

	.weak	LPTIM3_IRQHandler
	.thumb_set LPTIM3_IRQHandler,Default_Handler

	.weak	LPTIM4_IRQHandler
	.thumb_set LPTIM4_IRQHandler,Default_Handler

	.weak	LPTIM5_IRQHandler
	.thumb_set LPTIM5_IRQHandler,Default_Handler

	.weak	ETH1_LPI_IRQHandler
	.thumb_set ETH1_LPI_IRQHandler,Default_Handler

	.weak	RCC_WAKEUP_IRQHandler
	.thumb_set RCC_WAKEUP_IRQHandler,Default_Handler

	.weak	SAI4_IRQHandler
	.thumb_set SAI4_IRQHandler,Default_Handler

	.weak	DTS_IRQHandler
	.thumb_set DTS_IRQHandler,Default_Handler

	.weak	IWDG1_IT_IRQHandler
	.thumb_set IWDG1_IT_IRQHandler,Default_Handler

	.weak	IWDG2_IT_IRQHandler
	.thumb_set IWDG2_IT_IRQHandler,Default_Handler

	.weak	TAMP_S_IRQHandler
	.thumb_set TAMP_S_IRQHandler,Default_Handler

	.weak	RTC_WKUP_ALARM_S_IRQHandler
	.thumb_set RTC_WKUP_ALARM_S_IRQHandler,Default_Handler

	.weak	RTC_TS_S_IRQHandler
	.thumb_set RTC_TS_S_IRQHandler,Default_Handler

	.weak	DDRPERFM_IRQHandler
	.thumb_set DDRPERFM_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectonics *****END OF FILE****/
